export const icon = require('../../assets/image/pin_ref.png');
export const img1 = require('../../assets/image/pin.png');
export const img2 = require('../../assets/image/pin.png');
export const img3 = require('../../assets/image/pin.png');
export const img4 = require('../../assets/image/pin.png');
export const gridMaps = require('../../assets/image/Maps.jpg');
export const gridForm = require('../../assets/image/Form.png');
export const gridHomeHD = require('../../assets/image/HomeHD.jpg');
export const gridMenuMakan = require('../../assets/image/menumakaneskrim.jpg');
export const bgPicture = require('../../assets/image/pantai.jpg');
export const imageKerja = require('../../assets/image/tangerang.jpg');
export const close = require('../../assets/image/close.png');
export const Lamp = require('../../assets/image/Lamp.png');
export const QRIcon = require('../../assets/image/login_logo.png');
export const Checklist = require('../../assets/image/checklist.jpg');
export const Unchecklist = require('../../assets/image/unchecklist.png')
export const IconA = require('../../assets/image/logo_Seat_A.png'); //SeatScreen
export const IconB = require('../../assets/image/logo_Seat_B.png'); //SeatScreen
export const IconC = require('../../assets/image/logo_Seat_C.png'); //